add item to cart by name: id=add-to-cart-${dash separated itemname}
sorting dropdown: css=span.select_container
sorting option:
  lohi: xpath=//option[@value='lohi']
  hilo: xpath=//option[@value='hilo']
  az: xpath=//option[@value='az']
  za: xpath=//option[@value='za']
item name label: css=div.inventory_item_name
item price label: css=div.inventory_item_price